spring:
  servlet:
    multipart:
      max-file-size: 10MB        # 设置单个文件最大大小为10MB
      max-request-size: 100MB    # 设置多个文件大小为100MB

  #数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/digital_agriculture?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    devtools:
      #热部署生效,默认就是true
      restart:
        enabled: true
        exclude: application.yml,static
  redis:
    host: 127.0.0.1
    port: 6379
#分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名
  mapper-locations: classpath:mapper/*.xml
file:
  upload-path: F:\java project\graduation\img\
snowflake:
  data-center-id: 1 # 数据中心ID，可以使用机器IP地址最后一段数字，范围为0-31
  worker-id: 1 # 机器ID，可以使用服务器编号，范围为0-31
rocketmq:
  # 服务地址，多个用逗号分开
  name-server: localhost:9876
  producer:
    # 发送消息超时时间，默认3000
    send-message-timeout: 30000
    # 生产者组
    group: yzyGroup
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2
    # 异步消息重试此处，默认2
    retryTimesWhenSendAsyncFailed: 2
    # 消息最大长度，默认1024 * 1024 * 4(默认4M)
    maxMessageSize: 4096
    # 压缩消息阈值，默认4k(1024 * 4)
    compressMessageBodyThreshold: 4096
    # 是否在内部发送失败时重试另一个broker，默认false
    retryNextServer: false
  topic:
    pay: PAY_ORDER
    relation: RELATION
    sale: SALE_UPDATE
